spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        jdbc.batch_versioned_data: true

cron-expression:
  # Cron scheduler task for mass indexing Elasticsearch - every midnight 1st of the month
  past-month-turnover-updater: "0 0 0 1 * *"