spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
